In [2]:
import numpy as np

arr = np.arange(0,12,1).reshape(3,4).copy()

print(arr)

# indexing (단일 데이터 추출)
print(arr[2,3]) # 11

# slicing (연속적인 데이터 추출)
print(arr[1:2, 2]) # [6]

# Fancy indexing
# print(arr[행, 열])
print(arr[[0,2],2]) # [2 10]
# arr[[0번, 2번 행], 2번째 열]

print(arr[:,[0,2]])
'''
[[ 0  2]
 [ 4  6]
 [ 8 10]]
'''
# arr[처음~끝 행, [0번, 2번째 열]]


# 참고로 알아두세요
print(arr[[0,2], [0,2]])
# 추측
'''
0 2
8 10
'''
# 의미는 위에 있는게 맞는데 구조상 다르게 출력
# 그래서 ix_()함수를 제공해서 정상적으로 처리될 수 있게 해줘요
print(arr[np.ix_([0,2],[0,2])])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
11
[6]
[ 2 10]
[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 0 10]
[[ 0  2]
 [ 8 10]]


In [ ]:
# 사칙연산
# ndarray의 연산은 Python의 list와 완전히 다름
# 사칙연산(=, -,*,/)의 가장 큰 전제는
# 두개의 ndarray가 같은 shape이어야 해요
# 두번째로 같은 이치에 있는 놈들끼리 연산이 진행

arr1 = np.array([1,2,3,4,5,6]).reshape(2,3)
print(arr1)
'''
[[1 2 3]
 [4 5 6]]
'''

arr2 = np.array([10,20,30,40,50,60]).reshape(2,3)
print(arr2)
'''
[[10 20 30]
 [40 50 60]]
'''

print(arr1 + arr2) # arr1과 arr2의 각각의 자리 덧셈
'''
[[11 22 33]
 [44 55 66]]
'''

print(arr1 + 10) # 각 위치에 10을 더하는 연산 진행
'''              # 연산을 위해 차원을 증가 => broadcasting
[[11 12 13]
 [14 15 16]]
'''

print(arr1 + np.array([10, 20, 30]))
'''
[[1 2 3]    +   [10, 20, 30]
 [4 5 6]]       [10, 20, 30]

[[11 22 33]
 [14 25 36]]
'''

print(arr1 + np.array([10]))
'''
[[11 12 13]
 [14 15 16]]
'''

# 기억해야 하는 연산
# 2차원 행렬(matrix)에서 행렬곱이라는 연산이 있어요!


[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
[[11 22 33]
 [44 55 66]]
[[11 12 13]
 [14 15 16]]
[[11 22 33]
 [14 25 36]]
[[11 12 13]
 [14 15 16]]


In [ ]:
arr1 = np.arange(1, 13, 1).reshape(3,4)
arr2 = np.arange(1, 9, 1).reshape(4,2)

print(arr1)
'''
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
'''
print(arr2)
'''
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
'''

print(np.matmul(arr1, arr2))
'''
[[ 50  60]
 [114 140]
 [178 220]]
'''

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 50  60]
 [114 140]
 [178 220]]


In [ ]:
# Numpy가 제공하는 함수들
# 연산을 편하게 하기 위해서 제공되는 집계함수
# 합, 평균, 최대, 최소, 표준편차, 제곱근, 등등

arr = np.arange(1, 7, 1).reshape(2,3).copy()
print(arr.sum()) # 21
                 # 축이라는 개념
                 # axis(축)

# numpy는 집계연산을 할 때 축을 명시하지 않으면 axis가 None으로
# 간주하고 연산을 수행
# axis의 값은 1차원, 2차원, 3차원, 4차원, .... 다 사용할 수 있어요
# axis는 정수! 0부터 시작하는 정수
# ndarray 1차원은 축이 1개, axis값은 0만 사용가능
# ndarray 2차원은 축이 2개, axis는 0과 1을 사용 가능
# 0이 최고 차원(행) 1이 그 다음 차원(열)

21


In [32]:
# 집계함수

arr1 = np.array([1,2,3,4,5])

print(arr1.sum()) # Numpy는 axis를 명시하지 않으면 default로 None으로 설정
print(arr1.sum(axis=0)) # 15

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2.sum()) # 21
print(arr2.sum(axis=0)) # [5 7 9]
print(arr2.sum(axis=1)) # [6 15]

arr3 = np.array([1,2,3,4,5])
print(arr3.mean()) # 3.0
print(arr3.max()) # 5
print(arr3.min()) # 1
print(arr3.argmax()) # 4

15
15
21
[5 7 9]
[ 6 15]
3.0
5
1
4


In [98]:
# Series

import numpy as np
import pandas as pd

arr = np.array([-1, 5, 10, 99],
               dtype=np.float64)
print(arr) # [-1.  5. 10. 99.]

# 이렇게 생성하는건 좋지 않아요!
# Data 외곡이 너무 심한 문제
# arr1 = np.array([-1, 5, 10, 'Hello'])
# print(arr1) ['-1', '5', '10', 'Hello']

arr1 = np.array([-1, 5, 10, 'Hello'],
                dtype=object)
print(arr1)

# pandas의 Series를 생성 (본질은 ndarray)
# arr = np.array([-1, 5, 10, 99], dtype=np.float64)
s = pd.Series([-1, 5, 10, 99], dtype=np.float64)
print(s)
'''
0    -1.0
1     5.0
2    10.0
3    99.0
dtype: float64
인덱스 key값    인덱스 value값

dtype: 데이터 상태
'''
# 1. ndarray에 dictionary 기능이 추가된 개념
print(s.values) # [-1.  5. 10. 99.] (NumPy 배열)
print(s.index) # RangeIndex(start=0, stop=4, step=1) 인덱스 확인
print(s.dtype) # float64


[-1.  5. 10. 99.]
[-1 5 10 'Hello']
0    -1.0
1     5.0
2    10.0
3    99.0
dtype: float64
[-1.  5. 10. 99.]
RangeIndex(start=0, stop=4, step=1)
float64


In [104]:
s = pd.Series([1,5, -8, 10],
              dtype=np.float64,
              index=['c', 'ab', 'acd', 'k'])
# index 지정시, 출력하면 지정 index 출력

print(s)

# indexing은 어떻게 하나요
print(s['ab']) # 5.0
print(s[1]) # 5.0
# index인지 value값인지 헷갈려서 지정인덱스를 숫자로 주는건 좋지 않아요

c       1.0
ab      5.0
acd    -8.0
k      10.0
dtype: float64
5.0
5.0


/tmp/ipykernel_36344/2530001906.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[1]) # 5.0


In [113]:
s = pd.Series([1, 5, -8, 10],
              dtype=np.float64,
              index=['c', 'b', 'c', 'k']) # key값 중복작성 가능
print(s)
print(s['c']) # 2개가 있는데 어떤걸 가져오나요?
'''
c    1.0
c   -8.0
dtype: float64
# 모든 c의 value값을 출력
'''

c     1.0
b     5.0
c    -8.0
k    10.0
dtype: float64
c    1.0
c   -8.0
dtype: float64


In [115]:
s = pd.Series([1, 5, -8, 10],
              dtype=np.float64,
              index=['c', 'b', 'a', 'k']) # key값 중복작성 가능
print(s[0:2]) # ndarray의 slicing과 같아요!
'''
# slicing한 결과가 view인가요? copy인가요?
python list slicing -> copy
numpy list slicing -> view
pandas Series clicing -> 확정 불가
다만, pandas는 확정할 수 없어요. 만약 복사본이 필요하면
명확하게 copy()해야 해요
'''

c    1.0
b    5.0
dtype: float64


In [127]:
s = pd.Series(np.arange(1,7,1),
              dtype=np.float64,
              index=list('ABCDEF'))
print(s)

# Fancy indexing
s[['A', 'D', 'F']]

# Bollean Indexing
# 3의 배수만 출력 (broadcasting과 boolean indexing을 잘 이해해야 되요)
s[s.values % 3 == 0]
# s[s % 3 == 0] 가능!

# 당연히 집계함수도 제공되요!
print(s.sum())  # 21.0

A    1.0
B    2.0
C    3.0
D    4.0
E    5.0
F    6.0
dtype: float64


C    3.0
F    6.0
dtype: float64

In [134]:
# 결국 Series는 1차원 ndarray에 지정 index 개념을 붙여놓은거예요
# 지정 index와 values는 key와 value의 쌍의 관계예요
# 그래서 python의 dict를 이용해서 Series를 생성할 수 있어요

my_dict = {
    '서울':1000,
    '수원':3000,
    '제주':5000
}

s = pd.Series(my_dict)
print(s)

# 새로운 데이터를 추가 (인천 : 2000 추가)
s['인천'] = 2000
print(s)

# 데이터 삭제
s1 = s.drop('서울', inplace=False) # 기본값은 inplace = False
# inplace가 True 원본을 삭제
# inplace가 False 이면 복사본 생성 후 삭제
# 즉, False는 원본 변경 없음
print(f'원본 : \n{s}')
print(f'복사본 : \n{s1}')
'''
원본 : 
서울    1000
수원    3000
제주    5000
인천    2000
dtype: int64
복사본 : 
수원    3000
제주    5000
인천    2000
dtype: int64
'''

서울    1000
수원    3000
제주    5000
dtype: int64
서울    1000
수원    3000
제주    5000
인천    2000
dtype: int64
원본 : 
서울    1000
수원    3000
제주    5000
인천    2000
dtype: int64
복사본 : 
수원    3000
제주    5000
인천    2000
dtype: int64


In [190]:
# A 공장의 2019-01-01 부터 10일간 생산량을 Series로 저장
# 생산량은 평균이 50이고 표준편차가 5인 정규분포에서 random하게 생성(정수)
#         index    values
# 형식) 2019-01-01   52
#         .....     ....

# B 공장의 2019-01-05 부터 10일간 생산량을 Series로 저장
# 생산량은 평균이 70이고 표준편차가 8인 정규분포에서 random하게 생성(정수)
#         index    values
# 형식) 2019-01-01   52
#         .....     ....

# 날짜별로 모든 공장의 생산량 합계를 구하세요!

import numpy as np
import pandas as pd

from datetime import date, datetime, timedelta

# 난수의 재현을 위해 seed를 설정
np.random.seed(42)

startday_A = datetime(2019,1,1)
factory_A = pd.Series([int(x) for x in np.random.normal(50, 5, (10,))],
                     index=[startday_A + timedelta(days=x) for x in range(10)])

print(factory_A)
'''
2019-01-01    58
2019-01-02    52
2019-01-03    54
2019-01-04    61
2019-01-05    59
2019-01-06    45
2019-01-07    54
2019-01-08    49
2019-01-09    49
2019-01-10    52
dtype: int64
'''
startday_B = datetime(2019,1,5)
factory_B = pd.Series([int(x) for x in np.random.normal(70, 8, (10,))],
                     index=[startday_B + timedelta(days=x) for x in range(10)])

print(factory_B)
'''
2019-01-05    66
2019-01-06    66
2019-01-07    71
2019-01-08    54
2019-01-09    56
2019-01-10    65
2019-01-11    61
2019-01-12    72
2019-01-13    62
2019-01-14    58
dtype: int64
'''

print(factory_A + factory_B)
# Series는 반드시 index를 기준으로 연산이 수행되어야 해요!
# NaN => Not A Number 기본의미는 숫자가 아니다의 의미
#        다른 의미로 값이 없어요라는 의미도 가지고 있어요
# 1 + NaN = NaN
'''
2019-01-01      NaN
2019-01-02      NaN
2019-01-03      NaN
2019-01-04      NaN
2019-01-05    114.0
2019-01-06    114.0
2019-01-07    128.0
2019-01-08    107.0
2019-01-09    103.0
2019-01-10    117.0
2019-01-11      NaN
2019-01-12      NaN
2019-01-13      NaN
2019-01-14      NaN
dtype: float64
'''

# 그럼 우리가 원하는 결과를 만들려면 어떻게 해야해요?
# A 공장은 1월 1일 ~ 1월 14로 늘려줘야 해요, 단, 1월 11일 이후에는 생산량을 0으로 세팅
# B 공장은 1월 1일 ~ 1월 4일의 데이터를 생성해야 되요. 생산량은 0으로 세팅



2019-01-01    52
2019-01-02    49
2019-01-03    53
2019-01-04    57
2019-01-05    48
2019-01-06    48
2019-01-07    57
2019-01-08    53
2019-01-09    47
2019-01-10    52
dtype: int64
2019-01-05    66
2019-01-06    66
2019-01-07    71
2019-01-08    54
2019-01-09    56
2019-01-10    65
2019-01-11    61
2019-01-12    72
2019-01-13    62
2019-01-14    58
dtype: int64
2019-01-01      NaN
2019-01-02      NaN
2019-01-03      NaN
2019-01-04      NaN
2019-01-05    114.0
2019-01-06    114.0
2019-01-07    128.0
2019-01-08    107.0
2019-01-09    103.0
2019-01-10    117.0
2019-01-11      NaN
2019-01-12      NaN
2019-01-13      NaN
2019-01-14      NaN
dtype: float64


In [ ]:
index_a = set(factory_A.index)
index_b = set(factory_B.index)

index_a_b = index_a - index_b # 차집합
index_b_a = index_b - index_a # 차집합

for i in index_a_b:
    factory_B[i] = 0

for i in index_b_a:
    factory_A[i] = 0

print(factory_A + factory_B)
'''
2019-01-01     52
2019-01-02     49
2019-01-03     53
2019-01-04     57
2019-01-05    114
2019-01-06    114
2019-01-07    128
2019-01-08    107
2019-01-09    103
2019-01-10    117
2019-01-11     61
2019-01-12     72
2019-01-13     62
2019-01-14     58
Freq: D, dtype: int64
'''

# 연습문제

In [ ]:
ar1 = np.arange(0, 16, 1)
print(ar1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [36]:
ar2 = np.ones((5,5))
print(ar2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [37]:
ar3 = np.linspace(0,1,20)
print(ar3)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [39]:
# 4번
mean = 0
std = 1
ar4 = np.random.normal(mean, std, (3,4))
print(ar4)


[[ 1.48485722 -0.82717243 -0.57777464 -0.39964697]
 [ 0.36413449  1.35933167  0.46561134 -0.94847969]
 [ 0.78109711 -0.17812782  1.7244026  -0.09982972]]


In [40]:
# 5번
ar5 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]).reshape(3,3)
print(ar5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [42]:
# 6번
ar6 = np.zeros((5,5), dtype=np.int64)
ar6[1:4,1:4] = 1
print(ar6)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


In [5]:
# 7번
ar7 = np.arange(1,10,1).reshape(3,3)

print(ar7 * ar7)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [19]:
# 8번
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(np.vstack((a,b)))


[[1 2 3]
 [4 5 6]]


In [31]:
# 9번
ar9 = np.zeros((3,3), dtype=np.int64)
print(f'배열의 데이터 타입: {ar9.dtype}')
print(f'배열의 차원 수: {ar9.ndim}')
print(f'배열의 모양: {ar9.shape}')

배열의 데이터 타입: int64
배열의 차원 수: 2
배열의 모양: (3, 3)


In [32]:
# 10번
ar10 = np.random.randint(0,100,10)

print(ar10)

[31 85 89 30 27 64 38  2 50 51]


# ndarray indexing과 slicing

In [34]:
# 1번
arr1 = np.array([10, 20, 30, 40, 50])
print(arr1[2])

30


In [36]:
# 2번
arr2 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr2[1][1])

5


In [38]:
# 3번
arr3 = np.array([10, 20, 30, 40, 50])
print(arr3[1:4])

[20 30 40]


In [48]:
# 4번
arr4 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])

print(arr4[0:2,1:3])

[[2 3]
 [6 7]]


In [50]:
# 5번
arr5 = np.array([[[ 1,  2,  3],
                  [ 4,  5,  6]],

                 [[ 7,  8,  9],
                  [10, 11, 12]],

                 [[13, 14, 15],
                  [16, 17, 18]]])

print(arr5[1][0])

[7 8 9]


In [51]:
# 6번
arr6 = np.array([[ 1,  2,  3,  4],
                 [ 5,  6,  7,  8],
                 [ 9, 10, 11, 12],
                 [13, 14, 15, 16]])

print(np.diag(arr6))

[ 1  6 11 16]


In [60]:
# 7번
arr7 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr7[1::2])

[ 2  4  6  8 10]


In [62]:
# 8번
arr8 = np.array([[ 1,  2,  3,  4],
                 [ 5,  6,  7,  8],
                 [ 9, 10, 11, 12],
                 [13, 14, 15, 16]])
arr81 = np.hstack(arr8)
print(arr81[5:])

[ 6  7  8  9 10 11 12 13 14 15 16]


In [64]:
# 9번
arr9 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr9[3:6] = -1
print(arr9)

[ 0  1  2 -1 -1 -1  6  7  8  9]


In [67]:
# 10번
arr10 = np.array([[ 1,  2,  3,  4],
                  [ 5,  6,  7,  8],
                  [ 9, 10, 11, 12],
                  [13, 14, 15, 16]])

arr10[[0,3]] = 0
arr10[1:3,[0,3]] = 0
print(arr10)

[[ 0  0  0  0]
 [ 0  6  7  0]
 [ 0 10 11  0]
 [ 0  0  0  0]]


In [84]:
# 11번
arr = np.array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])
narr = []
for i in arr:
    if i >= 20 and i < 50:
        narr.append(i)

narr = np.array(narr)
print(narr)

[20 25 30 35 40 45]


In [199]:
# 12번
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(arr_2d[np.ix_([0,2],[1,3])])

[[ 2  4]
 [10 12]]


In [242]:
# 13번
arr13 = np.array([[12, 15, 22, 29],
                [5, 18, 21, 30],
                [14, 17, 13, 20]])

arr131 = np.hstack(arr)

for i in range(len(arr131)):
    if arr131[i] > 20:
        arr131[i] = 0

print(arr131.reshape((3,4)))

[[12 15  0  0]
 [ 5 18  0  0]
 [14 17 13 20]]


In [263]:
import numpy as np

# 배열 생성
arr = np.array([[10, 15, 20, 25],
                [30, 35, 40, 45],
                [50, 55, 60, 65],
                [70, 75, 80, 85]])

# 조건: 짝수 & 40보다 큰 값
condition = (arr % 2 == 0) & (arr > 40)

# 1. 조건에 맞는 인덱스 찾기
indices = np.where(condition)
print("조건을 만족하는 인덱스:", list(zip(indices[0], indices[1])))

# 2. 해당 위치 값 변경
arr[indices] = -1
print("요소 변경 후 배열:\n", arr)


조건을 만족하는 인덱스: [(np.int64(2), np.int64(0)), (np.int64(2), np.int64(2)), (np.int64(3), np.int64(0)), (np.int64(3), np.int64(2))]
요소 변경 후 배열:
 [[10 15 20 25]
 [30 35 40 45]
 [-1 55 -1 65]
 [-1 75 -1 85]]
